version: '3.9'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      MINECRAFT_VERSION: "1.19"
      FTP_USERNAME: ${FTP_USERNAME}
      FTP_PASS: ${FTP_PASS}
    image: minecraft_map
    container_name: minecraft_map
    volumes:
     - ./data/:/home/minecraft/.minecraft/
     - ./output/:/home/minecraft/output/
