version: '3.9'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MINECRAFT_VERSION: "1.19"
      CONFIG_LOCATION: /home/minecraft/.minecraft/config.py
      FTP_USERNAME: ${FTP_USERNAME}
      FTP_PASS: ${FTP_PASS}
      DOWNLOAD_WORLD: ${DOWNLOAD_WORLD}
    image: minecraft_map
    container_name: minecraft_map
    volumes:
     - ./data/:/home/minecraft/.minecraft/
     - ./output/:/home/minecraft/output/
    # Uncomment following when you want to persist world data
    #  - ./server/:/home/minecraft/server/