version: '3.9'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file: .env
    # environment:
    #  - RACK_ENV=.env
    #  - SHOW=true
    #  - USER_INPUT
    image: minecraft_map
    container_name: minecraft_map
    volumes:
     - ./data/:/home/minecraft/.minecraft/
     - ./output/:/home/minecraft/output/
